/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx public/models/avatargirl.glb 
*/

import React, { useEffect, useMemo, useRef, useState } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Avatar(props) {
  const group = useRef()
  const { scene } = useGLTF('models/avatargirl.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  

  const { animations: sittingAnimation } = useFBX('animations/Sitting.fbx')
  //   console.log(idleAnimation)
  sittingAnimation[0].name = 'Sitting';
  const { actions } = useAnimations(sittingAnimation, group)

  useEffect(() => {
    actions['Sitting'].reset().play()
  }, [])
  return (
    <group {...props} ref={group} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh name="Wolf3D_Avatar" geometry={nodes.Wolf3D_Avatar.geometry} material={materials.Wolf3D_Avatar} skeleton={nodes.Wolf3D_Avatar.skeleton} morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences} />

    </group>
  )
}

useGLTF.preload('models/avatargirl.glb')
